/**
 * Mock data for demo mode (no API key needed)
 * Simulates a realistic polling run with signals detected
 */

export const MOCK_PROFILES = [
  { id: 'p1', name: 'James Chen', company: 'Salesforce', title: 'VP Enterprise Sales', linkedinUrl: 'https://linkedin.com/in/jameschen', companyLinkedinUrl: 'https://linkedin.com/company/salesforce', status: 'active', addedAt: '2024-01-10T10:00:00Z', lastPolled: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: 'p2', name: 'Sarah Williams', company: 'HubSpot', title: 'Director of Revenue', linkedinUrl: 'https://linkedin.com/in/sarahwilliams', companyLinkedinUrl: 'https://linkedin.com/company/hubspot', status: 'changed', addedAt: '2024-01-10T10:00:00Z', lastPolled: new Date(Date.now() - 86400000).toISOString() },
  { id: 'p3', name: 'Raj Patel', company: 'Stripe', title: 'Head of Partnerships', linkedinUrl: 'https://linkedin.com/in/rajpatel', companyLinkedinUrl: 'https://linkedin.com/company/stripe', status: 'active', addedAt: '2024-01-15T10:00:00Z', lastPolled: new Date(Date.now() - 86400000 * 3).toISOString() },
  { id: 'p4', name: 'Emily Torres', company: 'Notion', title: 'Senior Account Executive', linkedinUrl: 'https://linkedin.com/in/emilytorres', companyLinkedinUrl: 'https://linkedin.com/company/notion', status: 'changed', addedAt: '2024-01-20T10:00:00Z', lastPolled: new Date(Date.now() - 86400000).toISOString() },
  { id: 'p5', name: 'Michael Park', company: 'Linear', title: 'CRO', linkedinUrl: 'https://linkedin.com/in/michaelpark', companyLinkedinUrl: 'https://linkedin.com/company/linear', status: 'active', addedAt: '2024-01-22T10:00:00Z', lastPolled: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: 'p6', name: 'Lisa Morgan', company: 'Figma', title: 'VP Marketing', linkedinUrl: 'https://linkedin.com/in/lisamorgan', companyLinkedinUrl: 'https://linkedin.com/company/figma', status: 'pending', addedAt: '2024-02-01T10:00:00Z', lastPolled: null },
  { id: 'p7', name: 'David Kim', company: 'Vercel', title: 'Director of Sales', linkedinUrl: 'https://linkedin.com/in/davidkim', companyLinkedinUrl: 'https://linkedin.com/company/vercel', status: 'active', addedAt: '2024-02-05T10:00:00Z', lastPolled: new Date(Date.now() - 86400000 * 7).toISOString() },
  { id: 'p8', name: 'Anna Rodriguez', company: 'Loom', title: 'Account Manager', linkedinUrl: 'https://linkedin.com/in/annarodriguez', companyLinkedinUrl: 'https://linkedin.com/company/loom', status: 'active', addedAt: '2024-02-10T10:00:00Z', lastPolled: new Date(Date.now() - 86400000 * 4).toISOString() },
];

export const MOCK_SIGNALS = [
  {
    id: 'sig-1',
    type: 'company_changed',
    priority: 'urgent',
    label: 'Changed Companies',
    emoji: '🚀',
    why: '<strong>Sarah Williams</strong> just moved from <strong>HubSpot</strong> to <strong>Rippling</strong>. She bought from you at HubSpot — reach out before competitors do.',
    action: 'Send warm intro',
    profile: 'Sarah Williams',
    company: 'Rippling',
    detectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    data: { prevCompany: 'HubSpot', currentCompany: 'Rippling' },
    dismissed: false,
  },
  {
    id: 'sig-2',
    type: 'new_exec_joined',
    priority: 'urgent',
    label: 'New Executive Joined',
    emoji: '👔',
    why: 'New <strong>VP of Engineering</strong> just joined <strong>Stripe</strong>. New execs evaluate vendors in their first 90 days.',
    action: 'Reach out now',
    profile: 'Raj Patel',
    company: 'Stripe',
    detectedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    data: { title: 'VP of Engineering', company: 'Stripe' },
    dismissed: false,
  },
  {
    id: 'sig-3',
    type: 'company_changed',
    priority: 'urgent',
    label: 'Changed Companies',
    emoji: '🚀',
    why: '<strong>Emily Torres</strong> just moved from <strong>Notion</strong> to <strong>Coda</strong>. Previous champion — reactivate this relationship immediately.',
    action: 'Send warm intro',
    profile: 'Emily Torres',
    company: 'Coda',
    detectedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    data: { prevCompany: 'Notion', currentCompany: 'Coda' },
    dismissed: false,
  },
  {
    id: 'sig-4',
    type: 'promoted',
    priority: 'week',
    label: 'Got Promoted',
    emoji: '⬆️',
    why: '<strong>James Chen</strong> was promoted to <strong>SVP Enterprise Sales</strong> at Salesforce. New title = new budget authority. Send a congratulations.',
    action: 'Send congrats',
    profile: 'James Chen',
    company: 'Salesforce',
    detectedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    data: { prevTitle: 'VP Enterprise Sales', title: 'SVP Enterprise Sales' },
    dismissed: false,
  },
  {
    id: 'sig-5',
    type: 'headcount_grew',
    priority: 'week',
    label: 'Team Growing Fast',
    emoji: '📈',
    why: '<strong>Linear</strong> headcount grew from <strong>45</strong> to <strong>78</strong> employees (+73%). Scaling teams need more tools.',
    action: 'Pitch expansion',
    profile: 'Michael Park',
    company: 'Linear',
    detectedAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    data: { prevHeadcount: 45, currentHeadcount: 78, growthPct: 73 },
    dismissed: false,
  },
  {
    id: 'sig-6',
    type: 'hiring_surge',
    priority: 'week',
    label: 'Hiring Surge Detected',
    emoji: '💼',
    why: '<strong>Figma</strong> is actively hiring <strong>12+</strong> roles in <strong>Sales & Revenue</strong>. Investment signal — reach out.',
    action: 'Target account',
    profile: 'Lisa Morgan',
    company: 'Figma',
    detectedAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    data: { openRoles: 12, department: 'Sales & Revenue' },
    dismissed: false,
  },
  {
    id: 'sig-7',
    type: 'location_changed',
    priority: 'watch',
    label: 'Location Changed',
    emoji: '📍',
    why: '<strong>David Kim</strong> moved from <strong>San Francisco, CA</strong> to <strong>New York, NY</strong>. Possible expansion or new market focus.',
    action: 'Monitor',
    profile: 'David Kim',
    company: 'Vercel',
    detectedAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    data: { prevLocation: 'San Francisco, CA', location: 'New York, NY' },
    dismissed: false,
  },
  {
    id: 'sig-8',
    type: 'company_went_quiet',
    priority: 'watch',
    label: 'Company Went Quiet',
    emoji: '🔇',
    why: '<strong>Loom</strong> hasn\'t posted in <strong>21 days</strong>. Unusual for their cadence. Monitor for churn risk.',
    action: 'Watch',
    profile: 'Anna Rodriguez',
    company: 'Loom',
    detectedAt: new Date(Date.now() - 3600000 * 96).toISOString(),
    data: { daysSilent: 21 },
    dismissed: false,
  },
];

export const MOCK_POLL_LOG = [
  { type: 'info', text: 'Starting poll for 8 profiles...' },
  { type: 'info', text: 'Polling Sarah Williams @ HubSpot...' },
  { type: 'signal', text: '🚀 SIGNAL: Sarah Williams changed companies → Rippling' },
  { type: 'success', text: '✓ James Chen — no change detected' },
  { type: 'success', text: '✓ Raj Patel — company page updated' },
  { type: 'signal', text: '👔 SIGNAL: New VP of Engineering joined Stripe' },
  { type: 'info', text: 'Polling Emily Torres @ Notion...' },
  { type: 'signal', text: '🚀 SIGNAL: Emily Torres changed companies → Coda' },
  { type: 'success', text: '✓ Michael Park — headcount change detected at Linear' },
  { type: 'signal', text: '📈 SIGNAL: Linear headcount grew 73%' },
  { type: 'success', text: '✓ Lisa Morgan — new job postings at Figma' },
  { type: 'signal', text: '💼 SIGNAL: Figma hiring surge in Sales & Revenue' },
  { type: 'success', text: '✓ David Kim — location changed' },
  { type: 'success', text: '✓ Anna Rodriguez — monitored' },
  { type: 'signal', text: '✅ Poll complete — 6 signals detected in 8 profiles' },
];

export const MOCK_CREDITS = {
  total: 500,
  used: 320,
  plan: 'Growth',
};
